### ISSUE TITLE
Task :web-interface:npm_run_build FAILED

### ISSUE THREAD

**Issue by wood-sheep** [4Benj/gcgm-plugin#3]
> Task :web-interface:npm_run_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web-interface:npm_run_build'.
> Process 'command '/root/resoureces/gcgm-plugin/gcgm-plugin/web-interface/.gradle/npm/npm-v8.1.2/bin/npm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by 4Benj** [comment]
Is there anything above the line `Task :web-interface:npm_run_build FAILED`?

**Comment by wood-sheep** [comment]
> 上面有什么东西`Task :web-interface:npm_run_build FAILED`吗？


This is all the information printed by the console

> Configure project :gc-plugin
Copying data from NPM output
Zipping web app files
Deleting non-zipped web app files

> Task :web-interface:npm_run_build

> web-interface@0.1.0 build
> cross-env PUBLIC_URL=/gm react-scripts build

Creating an optimized production build...
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.

> Task :web-interface:npm_run_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web-interface:npm_run_build'.
> Process 'command '/root/resoureces/gcgm-plugin/gcgm-plugin/web-interface/.gradle/npm/npm-v8.1.2/bin/npm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
6 actionable tasks: 1 executed, 5 up-to-date


My gradle version is 7.4.1 and npm version is 8.9.0 and nodejs v16.14.1
JVM:          17.0.3 (Eclipse Adoptium 17.0.3+7)
OS:           Linux 3.10.0-957.21.3.el7.x86_64 amd64

**Comment by 4Benj** [comment]
Are you running this in gcgm's root directory?

> This probably means the system ran out of memory or someone called kill -9 on the process.

Are you sure this didn't happen?

**Comment by wood-sheep** [comment]
> Are you running this in gcgm's root directory?
> 
> > This probably means the system ran out of memory or someone called kill -9 on the process.
> 
> Are you sure this didn't happen?

When I put the file in the / root directory and the build is successful, thank you for your help: -)
